name: sese

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: A debugger for actions
      run: |
        chmod +x diy.sh
        ./diy.sh
        ngrok config add-authtoken 2TmbyNIZE2s92Rf0UMAm6PAiz4v_46U6yh9UUw5mULpfxuQZ8
               
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4.1.0
      with:
        node-version: 18
    - run: npm install
    - run: npm run dev
