name: sese

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: A debugger for actions
      run: |

            
   
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4.1.0
      with:
        node-version: 18
    - run: npm install
    - run: npm run dev
